export const projects = [
  {
    id: '0000001',
    title: 'Plume Support',
    cover: 'https://i.postimg.cc/QNQ5Jyp2/project-1.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
  {
    id: '0000002',
    title: 'Plume Support',
    cover: 'https://i.postimg.cc/7Yqzsn9f/project-2.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
  {
    id: '0000003',
    title: 'Plume Support',
    cover: 'https://andrewhawkes.github.io/codepen-assets/steam-game-cards/game_3.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
  {
    id: '0000004',
    title: 'Plume Support',
    cover: 'https://andrewhawkes.github.io/codepen-assets/steam-game-cards/game_4.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
]
