export const projects = [
  {
    id: '0000001',
    title: 'Plume Support',
    cover: 'https://np-portfolio2020.s3.eu-west-2.amazonaws.com/assets/project_1.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
  {
    id: '0000002',
    title: 'Plume Support',
    cover: 'https://np-portfolio2020.s3.eu-west-2.amazonaws.com/assets/project_2.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
  {
    id: '0000003',
    title: 'Plume Support',
    cover: 'https://np-portfolio2020.s3.eu-west-2.amazonaws.com/assets/project_1.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
  {
    id: '0000004',
    title: 'Plume Support',
    cover: 'https://np-portfolio2020.s3.eu-west-2.amazonaws.com/assets/project_2.jpg',
    description: 'Plume Support website built with ...',
    usedTechnology: ['ZenDesk', 'HTML', 'SCSS', 'JavaScript'],
    publicCode: false,
    gitHubUrl: '',
    publicUrl: true,
    projectUrl: 'https://support.plume.com/',
  },
]
